# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVwOQpl-a7L3oS5S5RXjGgM68qgLxQi8
"""

import pandas as pd
import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go

qtd_loja_produto = pd.read_excel('data/quantidade_por_loja.xlsx')

qtd_loja_produto.head()

qtd_loja_produto['ID Loja'] = qtd_loja_produto['ID Loja'].ffill()

qtd_loja_produto.head()

fig = go.Figure()

lojas = qtd_loja_produto['ID Loja'].unique()

cores = px.colors.qualitative.Set2  # paleta do Plotly

for i, loja in enumerate(lojas):
    df_loja = qtd_loja_produto[qtd_loja_produto['ID Loja'] == loja]

    fig.add_trace(
        go.Bar(
            x=df_loja['Produto'],
            y=df_loja['Quantidade'],
            name=loja,
            visible=False,
            marker_color=cores[i % len(cores)]
        )
    )

# Primeira loja visível
fig.data[0].visible = True

# Dropdown
fig.update_layout(
    updatemenus=[
        {
            "buttons": [
                {
                    "label": loja,
                    "method": "update",
                    "args": [
                        {"visible": [i == idx for i in range(len(lojas))]},
                        {
                            "title": {
                                "text": f"Quantidade Vendida - {loja}",
                                "x": 0.5
                            }
                        }
                    ]
                }
                for idx, loja in enumerate(lojas)
            ],
            "direction": "down",
            "x": 0.1,
            "y": 1.15
        }
    ],
    title={
        "text": f"Quantidade Vendida - {lojas[0]}",
        "x": 0.5
    },
    xaxis_title="Produto",
    yaxis_title="Quantidade"
)

fig.write_html(
    "quantidade_vendida_por_loja.html",
    full_html=True,
    include_plotlyjs="cdn"
)

fig.write_html("index.html")

fig.show()